// <auto-generated />
using System;
using Infrastructure.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(LMSDbContext))]
    [Migration("20261003163335_AddSeedData")]
    partial class AddSeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.31")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.Question", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsLocked")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<Guid?>("PreviousQuestionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("TenantId");

                    b.HasIndex("TenantId", "IsDeleted");

                    b.ToTable("Question", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2026, 10, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            IsDeleted = false,
                            IsLocked = false,
                            TenantId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Text = "What is C#?"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000002"),
                            CreatedAt = new DateTime(2026, 10, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            IsDeleted = false,
                            IsLocked = false,
                            TenantId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Text = "What is Entity Framework Core?"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000003"),
                            CreatedAt = new DateTime(2026, 10, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            IsDeleted = false,
                            IsLocked = false,
                            TenantId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Text = "Which keyword is used to create a class in C#?"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000004"),
                            CreatedAt = new DateTime(2026, 10, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            IsDeleted = false,
                            IsLocked = false,
                            TenantId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Text = "What does API stand for?"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000005"),
                            CreatedAt = new DateTime(2026, 10, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            IsDeleted = false,
                            IsLocked = false,
                            TenantId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Text = "What is Dependency Injection?"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2026, 10, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = new Guid("cccccccc-cccc-cccc-cccc-cccccccccccc"),
                            IsDeleted = false,
                            IsLocked = false,
                            TenantId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Text = "What is LINQ?"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000002"),
                            CreatedAt = new DateTime(2026, 10, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = new Guid("cccccccc-cccc-cccc-cccc-cccccccccccc"),
                            IsDeleted = false,
                            IsLocked = false,
                            TenantId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Text = "What is a primary key?"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000003"),
                            CreatedAt = new DateTime(2026, 10, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = new Guid("cccccccc-cccc-cccc-cccc-cccccccccccc"),
                            IsDeleted = false,
                            IsLocked = false,
                            TenantId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Text = "What is a foreign key?"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000004"),
                            CreatedAt = new DateTime(2026, 10, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = new Guid("cccccccc-cccc-cccc-cccc-cccccccccccc"),
                            IsDeleted = false,
                            IsLocked = false,
                            TenantId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Text = "What is REST?"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000005"),
                            CreatedAt = new DateTime(2026, 10, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = new Guid("cccccccc-cccc-cccc-cccc-cccccccccccc"),
                            IsDeleted = false,
                            IsLocked = false,
                            TenantId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Text = "What is HTTP?"
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2026, 10, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = new Guid("eeeeeeee-eeee-eeee-eeee-eeeeeeeeeeee"),
                            IsDeleted = false,
                            IsLocked = false,
                            TenantId = new Guid("33333333-3333-3333-3333-333333333333"),
                            Text = "What is SQL?"
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000002"),
                            CreatedAt = new DateTime(2026, 10, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = new Guid("eeeeeeee-eeee-eeee-eeee-eeeeeeeeeeee"),
                            IsDeleted = false,
                            IsLocked = false,
                            TenantId = new Guid("33333333-3333-3333-3333-333333333333"),
                            Text = "What is a database index?"
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000003"),
                            CreatedAt = new DateTime(2026, 10, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = new Guid("eeeeeeee-eeee-eeee-eeee-eeeeeeeeeeee"),
                            IsDeleted = false,
                            IsLocked = false,
                            TenantId = new Guid("33333333-3333-3333-3333-333333333333"),
                            Text = "What is a database transaction?"
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000004"),
                            CreatedAt = new DateTime(2026, 10, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = new Guid("eeeeeeee-eeee-eeee-eeee-eeeeeeeeeeee"),
                            IsDeleted = false,
                            IsLocked = false,
                            TenantId = new Guid("33333333-3333-3333-3333-333333333333"),
                            Text = "What is optimistic concurrency?"
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000005"),
                            CreatedAt = new DateTime(2026, 10, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = new Guid("eeeeeeee-eeee-eeee-eeee-eeeeeeeeeeee"),
                            IsDeleted = false,
                            IsLocked = false,
                            TenantId = new Guid("33333333-3333-3333-3333-333333333333"),
                            Text = "What is a JWT?"
                        });
                });

            modelBuilder.Entity("Domain.Entities.QuestionChoice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsCorrect")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId");

                    b.ToTable("QuestionChoice", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("11000000-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2026, 10, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsCorrect = true,
                            QuestionId = new Guid("10000000-0000-0000-0000-000000000001"),
                            Text = "A programming language"
                        },
                        new
                        {
                            Id = new Guid("11000000-0000-0000-0000-000000000002"),
                            CreatedAt = new DateTime(2026, 10, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsCorrect = false,
                            QuestionId = new Guid("10000000-0000-0000-0000-000000000001"),
                            Text = "A database"
                        },
                        new
                        {
                            Id = new Guid("11000000-0000-0000-0000-000000000003"),
                            CreatedAt = new DateTime(2026, 10, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsCorrect = false,
                            QuestionId = new Guid("10000000-0000-0000-0000-000000000001"),
                            Text = "An operating system"
                        },
                        new
                        {
                            Id = new Guid("11000000-0000-0000-0000-000000000004"),
                            CreatedAt = new DateTime(2026, 10, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsCorrect = false,
                            QuestionId = new Guid("10000000-0000-0000-0000-000000000001"),
                            Text = "A web server"
                        },
                        new
                        {
                            Id = new Guid("12000000-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2026, 10, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsCorrect = true,
                            QuestionId = new Guid("10000000-0000-0000-0000-000000000002"),
                            Text = "An ORM for .NET"
                        },
                        new
                        {
                            Id = new Guid("12000000-0000-0000-0000-000000000002"),
                            CreatedAt = new DateTime(2026, 10, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsCorrect = false,
                            QuestionId = new Guid("10000000-0000-0000-0000-000000000002"),
                            Text = "A JavaScript framework"
                        },
                        new
                        {
                            Id = new Guid("12000000-0000-0000-0000-000000000003"),
                            CreatedAt = new DateTime(2026, 10, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsCorrect = false,
                            QuestionId = new Guid("10000000-0000-0000-0000-000000000002"),
                            Text = "A database engine"
                        },
                        new
                        {
                            Id = new Guid("12000000-0000-0000-0000-000000000004"),
                            CreatedAt = new DateTime(2026, 10, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsCorrect = false,
                            QuestionId = new Guid("10000000-0000-0000-0000-000000000002"),
                            Text = "An operating system"
                        },
                        new
                        {
                            Id = new Guid("13000000-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2026, 10, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsCorrect = true,
                            QuestionId = new Guid("10000000-0000-0000-0000-000000000003"),
                            Text = "class"
                        },
                        new
                        {
                            Id = new Guid("13000000-0000-0000-0000-000000000002"),
                            CreatedAt = new DateTime(2026, 10, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsCorrect = false,
                            QuestionId = new Guid("10000000-0000-0000-0000-000000000003"),
                            Text = "object"
                        },
                        new
                        {
                            Id = new Guid("13000000-0000-0000-0000-000000000003"),
                            CreatedAt = new DateTime(2026, 10, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsCorrect = false,
                            QuestionId = new Guid("10000000-0000-0000-0000-000000000003"),
                            Text = "newclass"
                        },
                        new
                        {
                            Id = new Guid("13000000-0000-0000-0000-000000000004"),
                            CreatedAt = new DateTime(2026, 10, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsCorrect = false,
                            QuestionId = new Guid("10000000-0000-0000-0000-000000000003"),
                            Text = "type"
                        },
                        new
                        {
                            Id = new Guid("14000000-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2026, 10, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsCorrect = true,
                            QuestionId = new Guid("10000000-0000-0000-0000-000000000004"),
                            Text = "Application Programming Interface"
                        },
                        new
                        {
                            Id = new Guid("14000000-0000-0000-0000-000000000002"),
                            CreatedAt = new DateTime(2026, 10, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsCorrect = false,
                            QuestionId = new Guid("10000000-0000-0000-0000-000000000004"),
                            Text = "Application Program Internet"
                        },
                        new
                        {
                            Id = new Guid("14000000-0000-0000-0000-000000000003"),
                            CreatedAt = new DateTime(2026, 10, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsCorrect = false,
                            QuestionId = new Guid("10000000-0000-0000-0000-000000000004"),
                            Text = "Advanced Programming Interface"
                        },
                        new
                        {
                            Id = new Guid("14000000-0000-0000-0000-000000000004"),
                            CreatedAt = new DateTime(2026, 10, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsCorrect = false,
                            QuestionId = new Guid("10000000-0000-0000-0000-000000000004"),
                            Text = "Application Process Integration"
                        },
                        new
                        {
                            Id = new Guid("15000000-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2026, 10, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsCorrect = true,
                            QuestionId = new Guid("10000000-0000-0000-0000-000000000005"),
                            Text = "A design pattern for providing dependencies"
                        },
                        new
                        {
                            Id = new Guid("15000000-0000-0000-0000-000000000002"),
                            CreatedAt = new DateTime(2026, 10, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsCorrect = false,
                            QuestionId = new Guid("10000000-0000-0000-0000-000000000005"),
                            Text = "A database type"
                        },
                        new
                        {
                            Id = new Guid("15000000-0000-0000-0000-000000000003"),
                            CreatedAt = new DateTime(2026, 10, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsCorrect = false,
                            QuestionId = new Guid("10000000-0000-0000-0000-000000000005"),
                            Text = "An HTTP protocol"
                        },
                        new
                        {
                            Id = new Guid("15000000-0000-0000-0000-000000000004"),
                            CreatedAt = new DateTime(2026, 10, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsCorrect = false,
                            QuestionId = new Guid("10000000-0000-0000-0000-000000000005"),
                            Text = "A testing framework"
                        },
                        new
                        {
                            Id = new Guid("21000000-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2026, 10, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsCorrect = true,
                            QuestionId = new Guid("20000000-0000-0000-0000-000000000001"),
                            Text = "Language Integrated Query"
                        },
                        new
                        {
                            Id = new Guid("21000000-0000-0000-0000-000000000002"),
                            CreatedAt = new DateTime(2026, 10, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsCorrect = false,
                            QuestionId = new Guid("20000000-0000-0000-0000-000000000001"),
                            Text = "Language Internal Query"
                        },
                        new
                        {
                            Id = new Guid("21000000-0000-0000-0000-000000000003"),
                            CreatedAt = new DateTime(2026, 10, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsCorrect = false,
                            QuestionId = new Guid("20000000-0000-0000-0000-000000000001"),
                            Text = "Logical Integrated Query"
                        },
                        new
                        {
                            Id = new Guid("21000000-0000-0000-0000-000000000004"),
                            CreatedAt = new DateTime(2026, 10, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsCorrect = false,
                            QuestionId = new Guid("20000000-0000-0000-0000-000000000001"),
                            Text = "Local Integrated Query"
                        },
                        new
                        {
                            Id = new Guid("22000000-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2026, 10, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsCorrect = true,
                            QuestionId = new Guid("20000000-0000-0000-0000-000000000002"),
                            Text = "Uniquely identifies a row"
                        },
                        new
                        {
                            Id = new Guid("22000000-0000-0000-0000-000000000002"),
                            CreatedAt = new DateTime(2026, 10, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsCorrect = false,
                            QuestionId = new Guid("20000000-0000-0000-0000-000000000002"),
                            Text = "Stores duplicate rows"
                        },
                        new
                        {
                            Id = new Guid("22000000-0000-0000-0000-000000000003"),
                            CreatedAt = new DateTime(2026, 10, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsCorrect = false,
                            QuestionId = new Guid("20000000-0000-0000-0000-000000000002"),
                            Text = "Connects to an API"
                        },
                        new
                        {
                            Id = new Guid("22000000-0000-0000-0000-000000000004"),
                            CreatedAt = new DateTime(2026, 10, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsCorrect = false,
                            QuestionId = new Guid("20000000-0000-0000-0000-000000000002"),
                            Text = "Stores a password"
                        },
                        new
                        {
                            Id = new Guid("23000000-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2026, 10, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsCorrect = true,
                            QuestionId = new Guid("20000000-0000-0000-0000-000000000003"),
                            Text = "References a key in another table"
                        },
                        new
                        {
                            Id = new Guid("23000000-0000-0000-0000-000000000002"),
                            CreatedAt = new DateTime(2026, 10, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsCorrect = false,
                            QuestionId = new Guid("20000000-0000-0000-0000-000000000003"),
                            Text = "Always contains unique values"
                        },
                        new
                        {
                            Id = new Guid("23000000-0000-0000-0000-000000000003"),
                            CreatedAt = new DateTime(2026, 10, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsCorrect = false,
                            QuestionId = new Guid("20000000-0000-0000-0000-000000000003"),
                            Text = "Is always a primary key"
                        },
                        new
                        {
                            Id = new Guid("23000000-0000-0000-0000-000000000004"),
                            CreatedAt = new DateTime(2026, 10, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsCorrect = false,
                            QuestionId = new Guid("20000000-0000-0000-0000-000000000003"),
                            Text = "Stores encrypted data"
                        },
                        new
                        {
                            Id = new Guid("24000000-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2026, 10, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsCorrect = true,
                            QuestionId = new Guid("20000000-0000-0000-0000-000000000004"),
                            Text = "Representational State Transfer"
                        },
                        new
                        {
                            Id = new Guid("24000000-0000-0000-0000-000000000002"),
                            CreatedAt = new DateTime(2026, 10, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsCorrect = false,
                            QuestionId = new Guid("20000000-0000-0000-0000-000000000004"),
                            Text = "Remote State Transfer"
                        },
                        new
                        {
                            Id = new Guid("24000000-0000-0000-0000-000000000003"),
                            CreatedAt = new DateTime(2026, 10, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsCorrect = false,
                            QuestionId = new Guid("20000000-0000-0000-0000-000000000004"),
                            Text = "Resource State Transaction"
                        },
                        new
                        {
                            Id = new Guid("24000000-0000-0000-0000-000000000004"),
                            CreatedAt = new DateTime(2026, 10, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsCorrect = false,
                            QuestionId = new Guid("20000000-0000-0000-0000-000000000004"),
                            Text = "Remote Service Technology"
                        },
                        new
                        {
                            Id = new Guid("25000000-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2026, 10, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsCorrect = true,
                            QuestionId = new Guid("20000000-0000-0000-0000-000000000005"),
                            Text = "HyperText Transfer Protocol"
                        },
                        new
                        {
                            Id = new Guid("25000000-0000-0000-0000-000000000002"),
                            CreatedAt = new DateTime(2026, 10, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsCorrect = false,
                            QuestionId = new Guid("20000000-0000-0000-0000-000000000005"),
                            Text = "High Transfer Text Protocol"
                        },
                        new
                        {
                            Id = new Guid("25000000-0000-0000-0000-000000000003"),
                            CreatedAt = new DateTime(2026, 10, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsCorrect = false,
                            QuestionId = new Guid("20000000-0000-0000-0000-000000000005"),
                            Text = "Hyper Transfer Type Protocol"
                        },
                        new
                        {
                            Id = new Guid("25000000-0000-0000-0000-000000000004"),
                            CreatedAt = new DateTime(2026, 10, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsCorrect = false,
                            QuestionId = new Guid("20000000-0000-0000-0000-000000000005"),
                            Text = "Host Transfer Protocol"
                        },
                        new
                        {
                            Id = new Guid("31000000-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2026, 10, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsCorrect = true,
                            QuestionId = new Guid("30000000-0000-0000-0000-000000000001"),
                            Text = "Structured Query Language"
                        },
                        new
                        {
                            Id = new Guid("31000000-0000-0000-0000-000000000002"),
                            CreatedAt = new DateTime(2026, 10, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsCorrect = false,
                            QuestionId = new Guid("30000000-0000-0000-0000-000000000001"),
                            Text = "Simple Query Language"
                        },
                        new
                        {
                            Id = new Guid("31000000-0000-0000-0000-000000000003"),
                            CreatedAt = new DateTime(2026, 10, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsCorrect = false,
                            QuestionId = new Guid("30000000-0000-0000-0000-000000000001"),
                            Text = "System Query Language"
                        },
                        new
                        {
                            Id = new Guid("31000000-0000-0000-0000-000000000004"),
                            CreatedAt = new DateTime(2026, 10, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsCorrect = false,
                            QuestionId = new Guid("30000000-0000-0000-0000-000000000001"),
                            Text = "Server Query Logic"
                        },
                        new
                        {
                            Id = new Guid("32000000-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2026, 10, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsCorrect = true,
                            QuestionId = new Guid("30000000-0000-0000-0000-000000000002"),
                            Text = "A data structure that improves query performance"
                        },
                        new
                        {
                            Id = new Guid("32000000-0000-0000-0000-000000000002"),
                            CreatedAt = new DateTime(2026, 10, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsCorrect = false,
                            QuestionId = new Guid("30000000-0000-0000-0000-000000000002"),
                            Text = "A database backup"
                        },
                        new
                        {
                            Id = new Guid("32000000-0000-0000-0000-000000000003"),
                            CreatedAt = new DateTime(2026, 10, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsCorrect = false,
                            QuestionId = new Guid("30000000-0000-0000-0000-000000000002"),
                            Text = "A database user"
                        },
                        new
                        {
                            Id = new Guid("32000000-0000-0000-0000-000000000004"),
                            CreatedAt = new DateTime(2026, 10, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsCorrect = false,
                            QuestionId = new Guid("30000000-0000-0000-0000-000000000002"),
                            Text = "A stored password"
                        },
                        new
                        {
                            Id = new Guid("33000000-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2026, 10, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsCorrect = true,
                            QuestionId = new Guid("30000000-0000-0000-0000-000000000003"),
                            Text = "A group of operations treated as one unit"
                        },
                        new
                        {
                            Id = new Guid("33000000-0000-0000-0000-000000000002"),
                            CreatedAt = new DateTime(2026, 10, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsCorrect = false,
                            QuestionId = new Guid("30000000-0000-0000-0000-000000000003"),
                            Text = "A database table"
                        },
                        new
                        {
                            Id = new Guid("33000000-0000-0000-0000-000000000003"),
                            CreatedAt = new DateTime(2026, 10, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsCorrect = false,
                            QuestionId = new Guid("30000000-0000-0000-0000-000000000003"),
                            Text = "A database index"
                        },
                        new
                        {
                            Id = new Guid("33000000-0000-0000-0000-000000000004"),
                            CreatedAt = new DateTime(2026, 10, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsCorrect = false,
                            QuestionId = new Guid("30000000-0000-0000-0000-000000000003"),
                            Text = "A user account"
                        },
                        new
                        {
                            Id = new Guid("34000000-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2026, 10, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsCorrect = true,
                            QuestionId = new Guid("30000000-0000-0000-0000-000000000004"),
                            Text = "Detecting changes using a version value"
                        },
                        new
                        {
                            Id = new Guid("34000000-0000-0000-0000-000000000002"),
                            CreatedAt = new DateTime(2026, 10, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsCorrect = false,
                            QuestionId = new Guid("30000000-0000-0000-0000-000000000004"),
                            Text = "Locking every database row"
                        },
                        new
                        {
                            Id = new Guid("34000000-0000-0000-0000-000000000003"),
                            CreatedAt = new DateTime(2026, 10, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsCorrect = false,
                            QuestionId = new Guid("30000000-0000-0000-0000-000000000004"),
                            Text = "Deleting duplicate records"
                        },
                        new
                        {
                            Id = new Guid("34000000-0000-0000-0000-000000000004"),
                            CreatedAt = new DateTime(2026, 10, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsCorrect = false,
                            QuestionId = new Guid("30000000-0000-0000-0000-000000000004"),
                            Text = "Encrypting database columns"
                        },
                        new
                        {
                            Id = new Guid("35000000-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2026, 10, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsCorrect = true,
                            QuestionId = new Guid("30000000-0000-0000-0000-000000000005"),
                            Text = "JSON Web Token"
                        },
                        new
                        {
                            Id = new Guid("35000000-0000-0000-0000-000000000002"),
                            CreatedAt = new DateTime(2026, 10, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsCorrect = false,
                            QuestionId = new Guid("30000000-0000-0000-0000-000000000005"),
                            Text = "Java Web Transfer"
                        },
                        new
                        {
                            Id = new Guid("35000000-0000-0000-0000-000000000003"),
                            CreatedAt = new DateTime(2026, 10, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsCorrect = false,
                            QuestionId = new Guid("30000000-0000-0000-0000-000000000005"),
                            Text = "JavaScript Web Token"
                        },
                        new
                        {
                            Id = new Guid("35000000-0000-0000-0000-000000000004"),
                            CreatedAt = new DateTime(2026, 10, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsCorrect = false,
                            QuestionId = new Guid("30000000-0000-0000-0000-000000000005"),
                            Text = "JSON Web Transfer"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Quiz", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int?>("MaxAttempts")
                        .HasColumnType("int");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("TenantId");

                    b.HasIndex("TenantId", "IsActive");

                    b.ToTable("Quiz", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2026, 10, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            Description = "Basic C# and .NET knowledge.",
                            IsActive = true,
                            MaxAttempts = 3,
                            TenantId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Title = "C# Fundamentals"
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0000-000000000002"),
                            CreatedAt = new DateTime(2026, 10, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            Description = "Backend development concepts.",
                            IsActive = true,
                            MaxAttempts = 2,
                            TenantId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Title = "Backend Fundamentals"
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0000-000000000003"),
                            CreatedAt = new DateTime(2026, 10, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = new Guid("cccccccc-cccc-cccc-cccc-cccccccccccc"),
                            Description = "SQL and relational database concepts.",
                            IsActive = true,
                            MaxAttempts = 3,
                            TenantId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Title = "Database Fundamentals"
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0000-000000000004"),
                            CreatedAt = new DateTime(2026, 10, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = new Guid("cccccccc-cccc-cccc-cccc-cccccccccccc"),
                            Description = "HTTP and REST concepts.",
                            IsActive = true,
                            TenantId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Title = "Web Fundamentals"
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0000-000000000005"),
                            CreatedAt = new DateTime(2026, 10, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = new Guid("eeeeeeee-eeee-eeee-eeee-eeeeeeeeeeee"),
                            Description = "Transactions and concurrency.",
                            IsActive = true,
                            MaxAttempts = 2,
                            TenantId = new Guid("33333333-3333-3333-3333-333333333333"),
                            Title = "Advanced Backend"
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0000-000000000006"),
                            CreatedAt = new DateTime(2026, 10, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = new Guid("eeeeeeee-eeee-eeee-eeee-eeeeeeeeeeee"),
                            Description = "Authentication and JWT concepts.",
                            IsActive = true,
                            MaxAttempts = 3,
                            TenantId = new Guid("33333333-3333-3333-3333-333333333333"),
                            Title = "Authentication"
                        });
                });

            modelBuilder.Entity("Domain.Entities.QuizAnswer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AttemptId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("bit");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("SelectedChoiceId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId");

                    b.HasIndex("SelectedChoiceId");

                    b.HasIndex("AttemptId", "QuestionId")
                        .IsUnique();

                    b.ToTable("QuizAnswer", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("51000000-0000-0000-0000-000000000001"),
                            AttemptId = new Guid("50000000-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2026, 10, 3, 1, 5, 0, 0, DateTimeKind.Utc),
                            IsCorrect = true,
                            QuestionId = new Guid("10000000-0000-0000-0000-000000000001"),
                            SelectedChoiceId = new Guid("11000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("51000000-0000-0000-0000-000000000002"),
                            AttemptId = new Guid("50000000-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2026, 10, 3, 1, 6, 0, 0, DateTimeKind.Utc),
                            IsCorrect = true,
                            QuestionId = new Guid("10000000-0000-0000-0000-000000000002"),
                            SelectedChoiceId = new Guid("12000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("51000000-0000-0000-0000-000000000003"),
                            AttemptId = new Guid("50000000-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2026, 10, 3, 1, 7, 0, 0, DateTimeKind.Utc),
                            IsCorrect = false,
                            QuestionId = new Guid("10000000-0000-0000-0000-000000000003"),
                            SelectedChoiceId = new Guid("13000000-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            Id = new Guid("51000000-0000-0000-0000-000000000004"),
                            AttemptId = new Guid("50000000-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2026, 10, 3, 1, 8, 0, 0, DateTimeKind.Utc),
                            IsCorrect = true,
                            QuestionId = new Guid("10000000-0000-0000-0000-000000000004"),
                            SelectedChoiceId = new Guid("14000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("51000000-0000-0000-0000-000000000005"),
                            AttemptId = new Guid("50000000-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2026, 10, 3, 1, 9, 0, 0, DateTimeKind.Utc),
                            IsCorrect = true,
                            QuestionId = new Guid("10000000-0000-0000-0000-000000000005"),
                            SelectedChoiceId = new Guid("15000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("52000000-0000-0000-0000-000000000001"),
                            AttemptId = new Guid("50000000-0000-0000-0000-000000000002"),
                            CreatedAt = new DateTime(2026, 10, 3, 2, 5, 0, 0, DateTimeKind.Utc),
                            IsCorrect = true,
                            QuestionId = new Guid("10000000-0000-0000-0000-000000000001"),
                            SelectedChoiceId = new Guid("11000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("52000000-0000-0000-0000-000000000002"),
                            AttemptId = new Guid("50000000-0000-0000-0000-000000000002"),
                            CreatedAt = new DateTime(2026, 10, 3, 2, 6, 0, 0, DateTimeKind.Utc),
                            IsCorrect = true,
                            QuestionId = new Guid("10000000-0000-0000-0000-000000000002"),
                            SelectedChoiceId = new Guid("12000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("52000000-0000-0000-0000-000000000003"),
                            AttemptId = new Guid("50000000-0000-0000-0000-000000000002"),
                            CreatedAt = new DateTime(2026, 10, 3, 2, 7, 0, 0, DateTimeKind.Utc),
                            IsCorrect = true,
                            QuestionId = new Guid("10000000-0000-0000-0000-000000000003"),
                            SelectedChoiceId = new Guid("13000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("52000000-0000-0000-0000-000000000004"),
                            AttemptId = new Guid("50000000-0000-0000-0000-000000000002"),
                            CreatedAt = new DateTime(2026, 10, 3, 2, 8, 0, 0, DateTimeKind.Utc),
                            IsCorrect = true,
                            QuestionId = new Guid("10000000-0000-0000-0000-000000000004"),
                            SelectedChoiceId = new Guid("14000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("52000000-0000-0000-0000-000000000005"),
                            AttemptId = new Guid("50000000-0000-0000-0000-000000000002"),
                            CreatedAt = new DateTime(2026, 10, 3, 2, 9, 0, 0, DateTimeKind.Utc),
                            IsCorrect = true,
                            QuestionId = new Guid("10000000-0000-0000-0000-000000000005"),
                            SelectedChoiceId = new Guid("15000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("54000000-0000-0000-0000-000000000001"),
                            AttemptId = new Guid("50000000-0000-0000-0000-000000000004"),
                            CreatedAt = new DateTime(2026, 10, 3, 1, 5, 0, 0, DateTimeKind.Utc),
                            IsCorrect = true,
                            QuestionId = new Guid("20000000-0000-0000-0000-000000000001"),
                            SelectedChoiceId = new Guid("21000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("54000000-0000-0000-0000-000000000002"),
                            AttemptId = new Guid("50000000-0000-0000-0000-000000000004"),
                            CreatedAt = new DateTime(2026, 10, 3, 1, 6, 0, 0, DateTimeKind.Utc),
                            IsCorrect = true,
                            QuestionId = new Guid("20000000-0000-0000-0000-000000000002"),
                            SelectedChoiceId = new Guid("22000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("54000000-0000-0000-0000-000000000003"),
                            AttemptId = new Guid("50000000-0000-0000-0000-000000000004"),
                            CreatedAt = new DateTime(2026, 10, 3, 1, 7, 0, 0, DateTimeKind.Utc),
                            IsCorrect = false,
                            QuestionId = new Guid("20000000-0000-0000-0000-000000000003"),
                            SelectedChoiceId = new Guid("23000000-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            Id = new Guid("55000000-0000-0000-0000-000000000001"),
                            AttemptId = new Guid("50000000-0000-0000-0000-000000000005"),
                            CreatedAt = new DateTime(2026, 10, 3, 2, 5, 0, 0, DateTimeKind.Utc),
                            IsCorrect = true,
                            QuestionId = new Guid("30000000-0000-0000-0000-000000000001"),
                            SelectedChoiceId = new Guid("31000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("55000000-0000-0000-0000-000000000002"),
                            AttemptId = new Guid("50000000-0000-0000-0000-000000000005"),
                            CreatedAt = new DateTime(2026, 10, 3, 2, 6, 0, 0, DateTimeKind.Utc),
                            IsCorrect = true,
                            QuestionId = new Guid("30000000-0000-0000-0000-000000000002"),
                            SelectedChoiceId = new Guid("32000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("55000000-0000-0000-0000-000000000003"),
                            AttemptId = new Guid("50000000-0000-0000-0000-000000000005"),
                            CreatedAt = new DateTime(2026, 10, 3, 2, 7, 0, 0, DateTimeKind.Utc),
                            IsCorrect = false,
                            QuestionId = new Guid("30000000-0000-0000-0000-000000000003"),
                            SelectedChoiceId = new Guid("33000000-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            Id = new Guid("55000000-0000-0000-0000-000000000004"),
                            AttemptId = new Guid("50000000-0000-0000-0000-000000000005"),
                            CreatedAt = new DateTime(2026, 10, 3, 2, 8, 0, 0, DateTimeKind.Utc),
                            IsCorrect = true,
                            QuestionId = new Guid("30000000-0000-0000-0000-000000000004"),
                            SelectedChoiceId = new Guid("34000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("56000000-0000-0000-0000-000000000001"),
                            AttemptId = new Guid("50000000-0000-0000-0000-000000000006"),
                            CreatedAt = new DateTime(2026, 10, 3, 4, 5, 0, 0, DateTimeKind.Utc),
                            IsCorrect = true,
                            QuestionId = new Guid("30000000-0000-0000-0000-000000000005"),
                            SelectedChoiceId = new Guid("35000000-0000-0000-0000-000000000001")
                        });
                });

            modelBuilder.Entity("Domain.Entities.QuizAttempt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Percentage")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)")
                        .HasDefaultValue(0m);

                    b.Property<Guid>("QuizId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("Score")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("SubmittedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("TotalQuestions")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("QuizId");

                    b.HasIndex("SubmittedAt");

                    b.HasIndex("StudentId", "QuizId");

                    b.HasIndex("TenantId", "QuizId");

                    b.HasIndex("TenantId", "StudentId");

                    b.ToTable("QuizAttempt", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("50000000-0000-0000-0000-000000000001"),
                            Percentage = 80m,
                            QuizId = new Guid("40000000-0000-0000-0000-000000000001"),
                            Score = 4,
                            StartedAt = new DateTime(2026, 10, 3, 1, 0, 0, 0, DateTimeKind.Utc),
                            Status = 2,
                            StudentId = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            SubmittedAt = new DateTime(2026, 10, 3, 1, 20, 0, 0, DateTimeKind.Utc),
                            TenantId = new Guid("11111111-1111-1111-1111-111111111111"),
                            TotalQuestions = 5
                        },
                        new
                        {
                            Id = new Guid("50000000-0000-0000-0000-000000000002"),
                            Percentage = 100m,
                            QuizId = new Guid("40000000-0000-0000-0000-000000000001"),
                            Score = 5,
                            StartedAt = new DateTime(2026, 10, 3, 2, 0, 0, 0, DateTimeKind.Utc),
                            Status = 2,
                            StudentId = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            SubmittedAt = new DateTime(2026, 10, 3, 2, 15, 0, 0, DateTimeKind.Utc),
                            TenantId = new Guid("11111111-1111-1111-1111-111111111111"),
                            TotalQuestions = 5
                        },
                        new
                        {
                            Id = new Guid("50000000-0000-0000-0000-000000000003"),
                            Percentage = 0m,
                            QuizId = new Guid("40000000-0000-0000-0000-000000000002"),
                            Score = 0,
                            StartedAt = new DateTime(2026, 10, 3, 3, 0, 0, 0, DateTimeKind.Utc),
                            Status = 1,
                            StudentId = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            TenantId = new Guid("11111111-1111-1111-1111-111111111111"),
                            TotalQuestions = 3
                        },
                        new
                        {
                            Id = new Guid("50000000-0000-0000-0000-000000000004"),
                            Percentage = 66.67m,
                            QuizId = new Guid("40000000-0000-0000-0000-000000000003"),
                            Score = 2,
                            StartedAt = new DateTime(2026, 10, 3, 1, 0, 0, 0, DateTimeKind.Utc),
                            Status = 2,
                            StudentId = new Guid("dddddddd-dddd-dddd-dddd-dddddddddddd"),
                            SubmittedAt = new DateTime(2026, 10, 3, 1, 25, 0, 0, DateTimeKind.Utc),
                            TenantId = new Guid("22222222-2222-2222-2222-222222222222"),
                            TotalQuestions = 3
                        },
                        new
                        {
                            Id = new Guid("50000000-0000-0000-0000-000000000005"),
                            Percentage = 75m,
                            QuizId = new Guid("40000000-0000-0000-0000-000000000005"),
                            Score = 3,
                            StartedAt = new DateTime(2026, 10, 3, 2, 0, 0, 0, DateTimeKind.Utc),
                            Status = 2,
                            StudentId = new Guid("ffffffff-ffff-ffff-ffff-ffffffffffff"),
                            SubmittedAt = new DateTime(2026, 10, 3, 2, 30, 0, 0, DateTimeKind.Utc),
                            TenantId = new Guid("33333333-3333-3333-3333-333333333333"),
                            TotalQuestions = 4
                        },
                        new
                        {
                            Id = new Guid("50000000-0000-0000-0000-000000000006"),
                            Percentage = 100m,
                            QuizId = new Guid("40000000-0000-0000-0000-000000000006"),
                            Score = 1,
                            StartedAt = new DateTime(2026, 10, 3, 4, 0, 0, 0, DateTimeKind.Utc),
                            Status = 2,
                            StudentId = new Guid("ffffffff-ffff-ffff-ffff-ffffffffffff"),
                            SubmittedAt = new DateTime(2026, 10, 3, 4, 10, 0, 0, DateTimeKind.Utc),
                            TenantId = new Guid("33333333-3333-3333-3333-333333333333"),
                            TotalQuestions = 1
                        });
                });

            modelBuilder.Entity("Domain.Entities.QuizQuestion", b =>
                {
                    b.Property<Guid>("QuizId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("DisplayOrder")
                        .HasColumnType("int");

                    b.HasKey("QuizId", "QuestionId");

                    b.HasIndex("QuestionId");

                    b.ToTable("QuizQuestion", (string)null);

                    b.HasData(
                        new
                        {
                            QuizId = new Guid("40000000-0000-0000-0000-000000000001"),
                            QuestionId = new Guid("10000000-0000-0000-0000-000000000001"),
                            DisplayOrder = 1
                        },
                        new
                        {
                            QuizId = new Guid("40000000-0000-0000-0000-000000000001"),
                            QuestionId = new Guid("10000000-0000-0000-0000-000000000002"),
                            DisplayOrder = 2
                        },
                        new
                        {
                            QuizId = new Guid("40000000-0000-0000-0000-000000000001"),
                            QuestionId = new Guid("10000000-0000-0000-0000-000000000003"),
                            DisplayOrder = 3
                        },
                        new
                        {
                            QuizId = new Guid("40000000-0000-0000-0000-000000000001"),
                            QuestionId = new Guid("10000000-0000-0000-0000-000000000004"),
                            DisplayOrder = 4
                        },
                        new
                        {
                            QuizId = new Guid("40000000-0000-0000-0000-000000000001"),
                            QuestionId = new Guid("10000000-0000-0000-0000-000000000005"),
                            DisplayOrder = 5
                        },
                        new
                        {
                            QuizId = new Guid("40000000-0000-0000-0000-000000000002"),
                            QuestionId = new Guid("10000000-0000-0000-0000-000000000002"),
                            DisplayOrder = 1
                        },
                        new
                        {
                            QuizId = new Guid("40000000-0000-0000-0000-000000000002"),
                            QuestionId = new Guid("10000000-0000-0000-0000-000000000004"),
                            DisplayOrder = 2
                        },
                        new
                        {
                            QuizId = new Guid("40000000-0000-0000-0000-000000000002"),
                            QuestionId = new Guid("10000000-0000-0000-0000-000000000005"),
                            DisplayOrder = 3
                        },
                        new
                        {
                            QuizId = new Guid("40000000-0000-0000-0000-000000000003"),
                            QuestionId = new Guid("20000000-0000-0000-0000-000000000001"),
                            DisplayOrder = 1
                        },
                        new
                        {
                            QuizId = new Guid("40000000-0000-0000-0000-000000000003"),
                            QuestionId = new Guid("20000000-0000-0000-0000-000000000002"),
                            DisplayOrder = 2
                        },
                        new
                        {
                            QuizId = new Guid("40000000-0000-0000-0000-000000000003"),
                            QuestionId = new Guid("20000000-0000-0000-0000-000000000003"),
                            DisplayOrder = 3
                        },
                        new
                        {
                            QuizId = new Guid("40000000-0000-0000-0000-000000000004"),
                            QuestionId = new Guid("20000000-0000-0000-0000-000000000004"),
                            DisplayOrder = 1
                        },
                        new
                        {
                            QuizId = new Guid("40000000-0000-0000-0000-000000000004"),
                            QuestionId = new Guid("20000000-0000-0000-0000-000000000005"),
                            DisplayOrder = 2
                        },
                        new
                        {
                            QuizId = new Guid("40000000-0000-0000-0000-000000000005"),
                            QuestionId = new Guid("30000000-0000-0000-0000-000000000001"),
                            DisplayOrder = 1
                        },
                        new
                        {
                            QuizId = new Guid("40000000-0000-0000-0000-000000000005"),
                            QuestionId = new Guid("30000000-0000-0000-0000-000000000002"),
                            DisplayOrder = 2
                        },
                        new
                        {
                            QuizId = new Guid("40000000-0000-0000-0000-000000000005"),
                            QuestionId = new Guid("30000000-0000-0000-0000-000000000003"),
                            DisplayOrder = 3
                        },
                        new
                        {
                            QuizId = new Guid("40000000-0000-0000-0000-000000000005"),
                            QuestionId = new Guid("30000000-0000-0000-0000-000000000004"),
                            DisplayOrder = 4
                        },
                        new
                        {
                            QuizId = new Guid("40000000-0000-0000-0000-000000000006"),
                            QuestionId = new Guid("30000000-0000-0000-0000-000000000005"),
                            DisplayOrder = 1
                        });
                });

            modelBuilder.Entity("Domain.Entities.Tenant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Tenant", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            CreatedAt = new DateTime(2026, 10, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Tenant 1",
                            UpdatedAt = new DateTime(2026, 10, 3, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            CreatedAt = new DateTime(2026, 10, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Tenant 2",
                            UpdatedAt = new DateTime(2026, 10, 3, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            CreatedAt = new DateTime(2026, 10, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Tenant 3",
                            UpdatedAt = new DateTime(2026, 10, 3, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.HasIndex("TenantId", "Email")
                        .IsUnique();

                    b.ToTable("User", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            CreatedAt = new DateTime(2026, 10, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "admin1@tenant1.com",
                            IsActive = true,
                            Name = "admin",
                            PasswordHash = "ECCXVLl1yRr/akfekaujGiWwjWD3QFa4m1ojq1fSZg4xMjM0",
                            PasswordSalt = "1234",
                            Role = 1,
                            TenantId = new Guid("11111111-1111-1111-1111-111111111111"),
                            UpdatedAt = new DateTime(2026, 10, 3, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            CreatedAt = new DateTime(2026, 10, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "student1@tenant1.com",
                            IsActive = true,
                            Name = "student",
                            PasswordHash = "MT6kNIiU0bP+QQQX4aWJIbIyXvYi5phudi0uwcmNAlIxMjM0",
                            PasswordSalt = "1234",
                            Role = 2,
                            TenantId = new Guid("11111111-1111-1111-1111-111111111111"),
                            UpdatedAt = new DateTime(2026, 10, 3, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("cccccccc-cccc-cccc-cccc-cccccccccccc"),
                            CreatedAt = new DateTime(2026, 10, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "admin2@tenant2.com",
                            IsActive = true,
                            Name = "admin",
                            PasswordHash = "ECCXVLl1yRr/akfekaujGiWwjWD3QFa4m1ojq1fSZg4xMjM0",
                            PasswordSalt = "1234",
                            Role = 1,
                            TenantId = new Guid("22222222-2222-2222-2222-222222222222"),
                            UpdatedAt = new DateTime(2026, 10, 3, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("dddddddd-dddd-dddd-dddd-dddddddddddd"),
                            CreatedAt = new DateTime(2026, 10, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "student2@tenant2.com",
                            IsActive = true,
                            Name = "student",
                            PasswordHash = "MT6kNIiU0bP+QQQX4aWJIbIyXvYi5phudi0uwcmNAlIxMjM0",
                            PasswordSalt = "1234",
                            Role = 2,
                            TenantId = new Guid("22222222-2222-2222-2222-222222222222"),
                            UpdatedAt = new DateTime(2026, 10, 3, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("eeeeeeee-eeee-eeee-eeee-eeeeeeeeeeee"),
                            CreatedAt = new DateTime(2026, 10, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "admin3@tenant3.com",
                            IsActive = true,
                            Name = "admin",
                            PasswordHash = "ECCXVLl1yRr/akfekaujGiWwjWD3QFa4m1ojq1fSZg4xMjM0",
                            PasswordSalt = "1234",
                            Role = 1,
                            TenantId = new Guid("33333333-3333-3333-3333-333333333333"),
                            UpdatedAt = new DateTime(2026, 10, 3, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("ffffffff-ffff-ffff-ffff-ffffffffffff"),
                            CreatedAt = new DateTime(2026, 10, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "student3@tenant3.com",
                            IsActive = true,
                            Name = "student",
                            PasswordHash = "MT6kNIiU0bP+QQQX4aWJIbIyXvYi5phudi0uwcmNAlIxMjM0",
                            PasswordSalt = "1234",
                            Role = 2,
                            TenantId = new Guid("33333333-3333-3333-3333-333333333333"),
                            UpdatedAt = new DateTime(2026, 10, 3, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("Domain.Entities.Question", b =>
                {
                    b.HasOne("Domain.Entities.User", "CreatedByUser")
                        .WithMany("CreatedQuestions")
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Tenant", "Tenant")
                        .WithMany("Questions")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreatedByUser");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Domain.Entities.QuestionChoice", b =>
                {
                    b.HasOne("Domain.Entities.Question", "Question")
                        .WithMany("Choices")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Question");
                });

            modelBuilder.Entity("Domain.Entities.Quiz", b =>
                {
                    b.HasOne("Domain.Entities.User", "CreatedByUser")
                        .WithMany("CreatedQuizzes")
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Tenant", "Tenant")
                        .WithMany("Quizzes")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreatedByUser");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Domain.Entities.QuizAnswer", b =>
                {
                    b.HasOne("Domain.Entities.QuizAttempt", "Attempt")
                        .WithMany("Answers")
                        .HasForeignKey("AttemptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Question", "Question")
                        .WithMany()
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.QuestionChoice", "SelectedChoice")
                        .WithMany("QuizAnswers")
                        .HasForeignKey("SelectedChoiceId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Attempt");

                    b.Navigation("Question");

                    b.Navigation("SelectedChoice");
                });

            modelBuilder.Entity("Domain.Entities.QuizAttempt", b =>
                {
                    b.HasOne("Domain.Entities.Quiz", "Quiz")
                        .WithMany("Attempts")
                        .HasForeignKey("QuizId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.User", "Student")
                        .WithMany("Attempts")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Quiz");

                    b.Navigation("Student");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Domain.Entities.QuizQuestion", b =>
                {
                    b.HasOne("Domain.Entities.Question", "Question")
                        .WithMany("QuizQuestions")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Quiz", "Quiz")
                        .WithMany("QuizQuestions")
                        .HasForeignKey("QuizId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Question");

                    b.Navigation("Quiz");
                });

            modelBuilder.Entity("Domain.Entities.User", b =>
                {
                    b.HasOne("Domain.Entities.Tenant", "Tenant")
                        .WithMany("Users")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Domain.Entities.Question", b =>
                {
                    b.Navigation("Choices");

                    b.Navigation("QuizQuestions");
                });

            modelBuilder.Entity("Domain.Entities.QuestionChoice", b =>
                {
                    b.Navigation("QuizAnswers");
                });

            modelBuilder.Entity("Domain.Entities.Quiz", b =>
                {
                    b.Navigation("Attempts");

                    b.Navigation("QuizQuestions");
                });

            modelBuilder.Entity("Domain.Entities.QuizAttempt", b =>
                {
                    b.Navigation("Answers");
                });

            modelBuilder.Entity("Domain.Entities.Tenant", b =>
                {
                    b.Navigation("Questions");

                    b.Navigation("Quizzes");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("Domain.Entities.User", b =>
                {
                    b.Navigation("Attempts");

                    b.Navigation("CreatedQuestions");

                    b.Navigation("CreatedQuizzes");
                });
#pragma warning restore 612, 618
        }
    }
}
